# Generated by Django 4.0.5 on 2022-07-02 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generic', '0002_remove_person_person_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cycle_Stage_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application', to='applications.cycle')),
                ('stage_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application', to='applications.stage')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_statge_link_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application', to='applications.cycle_stage_link')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application', to='generic.person')),
            ],
        ),
    ]
