# Generated by Django 4.0.5 on 2022-07-04 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_email_alter_student_mobile_and_more'),
        ('employees', '0003_alter_employee_mobile_alter_employee_national_id'),
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='current_statge_link_id',
        ),
        migrations.RemoveField(
            model_name='application',
            name='person_id',
        ),
        migrations.AddField(
            model_name='application',
            name='application_number',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='current_cycle_stage_link_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='applications.cycle_stage_link'),
        ),
        migrations.AddField(
            model_name='application',
            name='current_employee_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='application',
            name='student_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='students.student'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cycle',
            name='document',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cycle_stage_link',
            name='cycle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stages', to='applications.cycle'),
        ),
        migrations.AlterField(
            model_name='cycle_stage_link',
            name='stage_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cyclelinked', to='applications.stage'),
        ),
    ]
