# Generated by Django 4.0.5 on 2022-07-01 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Study_Specialize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_specialize', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Study_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.IntegerField()),
                ('term_no', models.IntegerField()),
                ('student_code', models.IntegerField()),
                ('study_specialize_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.study_specialize')),
                ('study_type_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.study_type')),
            ],
        ),
    ]
