# Generated by Django 4.0.5 on 2022-07-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_overall_rating_student_person_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='person_id',
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mobile',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='national_id',
            field=models.CharField(max_length=14, null=True),
        ),
    ]
